import Head from 'next/head'
import Image from 'next/image'
import { Grid } from '@/components/SingleGrid/SingleGrid'
import { Grid as DoubleGrid } from '@/components/DoubleGrid/DoubleGrid'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Grid 
          type='header'
          title='Hello World'
          backgroundColor='#2f2e41'
          isDark={true}
        />
        <DoubleGrid
          title='About me'
          backgroundColor={null}
          isDark={true}
        />
        <DoubleGrid
          title='Contact me'
          backgroundColor='#2f2e41'
          isDark={true}
        />
        <Grid 
          type='footer'
          title='Fin.'
          backgroundColor='white'
          isDark={false}
        />
      </div>
    </>
  )
}
